### ISSUE TITLE
Outline and write work priorities blog

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/blog-nrrd#360]

**Comment by lpgoldstein** [comment]
@cthomasONRR and @alexandracmONRR do you have time to review the blog? https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/Work%20priorities.docx?d=w4e054936ce3646388849270b451d63ff&csf=1&web=1&e=wMjnrp

**Comment by cthomasONRR** [comment]
@lpgoldstein I read the blog and left some comments. I'm happy to do a second pass later as well. Thanks!

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - i've also finished my read through and left comments/some edits. Let me know if you need more help/review!

**Comment by eelzi-ONRR** [comment]
@lpgoldstein I added a folder in the blog-in progress folder for work priorities images and put two in there. If they look blurry or meh we can scrap them - we're limited in how we can pull them since we use the free version of miro. Captions and alt text are in the blog doc - I highlighted them so it's easy to find. Thanks for making the PR!
