### ISSUE TITLE
Review blog notifications prototypes

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/blog-nrrd#387]
[Prototypes link](https://tolzyf.axshare.com/#g=14):

- Homepage: options 1-4
- Individual Blog pages: options A-B

These prototypes aim to improve 2 recommendations:
- Add **RSS link and icon** (#375) [header and footer]
- Make **home button** more obvious (#380) [header and bottom of blog page]

Other recommendations to consider/comment on:

- **Blog title/subtitle**: Add subtitle or blurb or about page that explain we're part of DOI and the general subject matter of the blog
- **RSS info page**: Add info that teaches users more about RSS and how it fits in with our open data mission

**Comment by AlexandracmONRR** [comment]
Feedback provided at sync up on 8/6/2024
- Prototype 3: Try putting the nav buttons to RSS link, RSS info page, and about us below the logo and title
- Prototype 4: Try a adding a hero image/background. This could provide consistency in motif with ONRR.gov and a banner.

**Comment by cthomasONRR** [comment]
Reiterating some of my comments from standup:

HOMEPAGE
- Prototype 3: I like this one, and second Jeff's comments about moving the 3 links that are current on the far top right to below the the logo and title.  
- Prototype 4: I still like this one too. I will defer to Jeff's decision if this banner concept is too annoying/difficult. 
- For the title, I don't like having "ODDD" and think it needs to be defined. Did anyone specifically have issues with "Open data, design, & development at the Office of Natural Resources Revenue"?  I feel strongly that "Open data, design, & development" needs to be spelled out in the title.
    - For title, what about "Open data, design, & development team blog"

BLOG PAGE
- I think we need to defer to what Jeff said about the content in the far right and left possibly being annoying to code.
- If all content needs to stay in the center column (where the blog text/content is), what about flipping the website title and logo... so "Open data, design, & development team blog" text first, under that the bison logo, under that the RSS link, THEN the blog content. 
    - Or, instead of the bison logo, a simple text "Home" link. Were people are confused that the bison is clickable?
- Prototype A. If content can be in that far left and right corners, what about adding a "Home" text link before About us and RSS links? I'd also be interested in seeing these 3 links in a column instead of a row.
- Prototype B: pretty much the same comment as A... if we can add links to the far right, maybe an addition text "Home" link would clarify a lot. 
- We can keep the bison logo link but also have the home text link.... if people are confused that the bison is clickable, then maybe have 2 options will resolve this issue.

**Comment by lpgoldstein** [comment]
Homepage

- I like #3 and agree that we should spell out the team name. "Open data, design, & development team blog" for the name
-  For the about us, RSS feed at the top - I defer to whatever Jeff says is easier. I prefer the corner if we have a choice. I don't like the about our team pop up in the center. It adds more white space to the page and pushes the blog further down.

**Comment by AlexandracmONRR** [comment]
Lindsay: 
Homepage: Prototype 3
Blog page: leave as is now (title underneath with blog in it) and then home button at the bottom.
Footer: no preference, all are good (depends on what is easiest to develop)

**Comment by AlexandracmONRR** [comment]
Erin:
	- I really like 4, but with maybe an even more narrow hero image.. My second choice would be 3 - I like the location and look of the RSS links in both, and the simple explanation of what the blog is in 3. The blue bar in 3B and 3C is too eye-catching - it's the first thing I see and it's distracting after that - I don't think that's what you want. I like B for the blog page - I think the home icon is obvious what it is and moving the buffalo to the corner also makes it seem more like a homepage link.
Personally, I like 1 - where it just subtlety adds the RSS icon and about link. But I think in the research people commented that they like it when both an icon and label are given, so in then I my preference is number 3

**Comment by AlexandracmONRR** [comment]
Gathered the input, and will move forward with 2 prototypes for hallway testing.
